# Generated by Django 3.2.9 on 2022-12-14 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-date_added']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='created_at',
            new_name='date_added',
        ),
    ]
